---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
lint: |   
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
verifier:
  name: ansible
